### ISSUE TITLE
AstraProjector3DSimple norm throws an error

### ISSUE THREAD

**Issue by paskino** [vais-ral/CCPi-astra#51]
running `norm` on a `AstraProjector3DSimple` results in the following exception

```
======================================================================
ERROR: test_norm_simple3D (test_AstraOperators.TestAstraSimple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/edo/GitHub/CCPi-Astra/Wrappers/Python/test/test_AstraOperators.py", line 86, in test_norm_simple3D
    n = self.A3.norm()
  File "/home/edo/miniconda3/envs/astra/lib/python3.6/site-packages/ccpi/astra/operators/AstraProjector3DSimple.py", line 75, in norm
    self.s1, sall, svec = LinearOperator.PowerMethod(self, 50, x0)
  File "/home/edo/miniconda3/envs/astra/lib/python3.6/site-packages/ccpi/optimisation/operators/LinearOperator.py", line 56, in PowerMethod
    operator.direct(x0,out=y_tmp)
  File "/home/edo/miniconda3/envs/astra/lib/python3.6/site-packages/ccpi/astra/operators/AstraProjector3DSimple.py", line 57, in direct
    out.fill(self.fp.get_output())
  File "/home/edo/miniconda3/envs/astra/lib/python3.6/site-packages/ccpi/framework/framework.py", line 1349, in get_output
    self.output = self.process(out=out)
  File "/home/edo/miniconda3/envs/astra/lib/python3.6/site-packages/ccpi/astra/processors/AstraForwardProjector3D.py", line 66, in process
    self.vol_geom)
  File "/home/edo/miniconda3/envs/astra/lib/python3.6/site-packages/astra/creators.py", line 421, in create_sino3d_gpu
    volume_id = data3d.create('-vol', vol_geom, data)
  File "/home/edo/miniconda3/envs/astra/lib/python3.6/site-packages/astra/data3d.py", line 43, in create
    return d.create(datatype,geometry,data)
  File "astra/data3d_c.pyx", line 102, in astra.data3d_c.create
RuntimeError: Geometry class not initialized.

----------------------------------------------------------------------
```

See #50

**Comment by paskino** [comment]
That's due to misconfiguration of the `AcquisitionGeometry` instance. 
Fixed in #58
